//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveFileGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstantValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaveFileGenerator.Resources.ConstantValues", typeof(ConstantValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIFF.
        /// </summary>
        internal static string _00_RiffText {
            get {
                return ResourceManager.GetString("00_RiffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAVE.
        /// </summary>
        internal static string _01_WaveFormatValue {
            get {
                return ResourceManager.GetString("01_WaveFormatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fmt.
        /// </summary>
        internal static string _02_FmtValue {
            get {
                return ResourceManager.GetString("02_FmtValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        internal static string _03_DataValue {
            get {
                return ResourceManager.GetString("03_DataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.wav.
        /// </summary>
        internal static string _04_DefaultFilename {
            get {
                return ResourceManager.GetString("04_DefaultFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 440hz_second.wav.
        /// </summary>
        internal static string NAME005_440HzFilename {
            get {
                return ResourceManager.GetString("NAME005_440HzFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mio_mao.wav.
        /// </summary>
        internal static string NAME006_MioMaoTestFileName {
            get {
                return ResourceManager.GetString("NAME006_MioMaoTestFileName", resourceCulture);
            }
        }
    }
}
